# Generated by Django 4.0 on 2021-12-20 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Browsers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'browsers',
            },
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('memory', models.IntegerField()),
                ('brand', models.CharField(max_length=20)),
                ('browser_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='browsersPc.browsers')),
            ],
            options={
                'db_table': 'pc',
            },
        ),
    ]
